# Generated by Django 6.0.1 on 2026-01-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_study_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_hours_per_day',
        ),
    ]
