# Generated by Django 6.0.1 on 2026-01-29 14:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        ('subjects', '0008_alter_chapter_options_alter_chapter_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyschedule',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.chapter'),
        ),
        migrations.AlterModelOptions(
            name='studyschedule',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='studyschedule',
            old_name='is_completed',
            new_name='generated_by_ai',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='actual_time_spent',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='time_allocated',
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 29, 14, 3, 23, 664342, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 29, 14, 3, 30, 464790, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 29, 14, 3, 44, 705811, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='task_type',
            field=models.CharField(choices=[('study', 'Study'), ('revision', 'Revision'), ('practice', 'Practice'), ('exam', 'Exam Prep')], default=datetime.datetime(2026, 1, 29, 14, 3, 58, 858653, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyschedule',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('subject', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('user', 'day', 'start_time')},
            },
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
