# Generated by Django 6.0.1 on 2026-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_studyschedule_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
