# Generated by Django 6.0.1 on 2026-03-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0003_remove_subject_total_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter'),
        ),
    ]
