# Generated by Django 6.0.1 on 2026-03-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='chapter',
        ),
    ]
