# Generated by Django 6.0.1 on 2026-01-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt'),
        ('subjects', '0004_remove_question_created_at_question_options_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='chapter',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_possible',
            field=models.IntegerField(default=0),
        ),
    ]
