# Generated by Django 6.0.1 on 2026-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_chapters',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
