# Generated by Django 6.0.1 on 2026-01-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='chapters/notes/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.subject')),
            ],
            options={
                'unique_together': {('subject', 'chapter_number')},
            },
        ),
    ]
