# Generated by Django 6.0.1 on 2026-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_total_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='total_chapters',
        ),
    ]
