# Generated by Django 6.0.1 on 2026-01-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_question_created_at_question_options_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='completed_chapters',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_chapters',
        ),
    ]
