# Generated by Django 6.0.1 on 2026-01-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_chapter_is_not_pdf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject',)},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_number',
        ),
    ]
