# Generated by Django 6.0.1 on 2026-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_number')},
        ),
    ]
